#!/bin/bash

echo "Enter Container Image"

read image

echo "Enter Pod Name"

read deployment

username=$(whoami)

nodeport=30040

cat <<EOF >$HOME/${username}-dep.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: $deployment
  labels:
    app: $deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: $deployment
  template:
    metadata:
      labels:
        app: $deployment
    spec:
      containers:
      - name: $deployment
        image: $image
        env:
        - name: HOME
          value: $HOME
        ports:
        - containerPort: 8501
        command: [ "/bin/bash", "-c" ]
        args: [ "while true; do sleep 1; done;" ] 
        resources:
          limits:
            nvidia.com/gpu: 0
        volumeMounts:
        - name: raid
          mountPath: /workspace
      volumes:
      - name: raid
        hostPath:
          path: /raid/dlops-course/$username
          type: Directory
EOF

cd $HOME

kubectl create -f ${username}-dep.yaml

cat <<EOF >$HOME/${username}-svc.yaml

kind: Service
apiVersion: v1
metadata:
  name: $deployment
spec:
  type: NodePort
  selector:
    app: $deployment
  ports:
  - protocol: TCP
    nodePort:
    port: 8501
    targetPort: 8501
EOF


kubectl create -f ${username}-svc.yaml
rm ${username}-dep.yaml
rm ${username}-svc.yaml
sleep 10
host_ip="$(hostname -I | cut -f1 -d' ')"

podname=$( kubectl get pod |grep -w "$deployment"|awk '{print $1}')


jup_token="$(kubectl logs $podname |grep token|awk '{print $4}'|awk '{print substr($0,29,77)}')"


svc_nodeport="$(kubectl describe svc $deployment |awk '{if ($1=="NodePort:") print $3}'|awk '{print substr($0,1,5)}')"

host_ip_link="$(echo "http://172.25.0.42:$svc_nodeport")"

echo "Welcome to NVIDIA DGX A100 Cluster. Kindly paste the given URL onto your browser $host_ip_link"

echo $host_ip_link > client-login-$deployment.txt
